steps:
  - label: "Run Metabase tests (Linux) (x86_64)"
    key: "metabase-tests-linux_x86_64"
    command: "node --experimental-fetch ./.buildkite/runtime-tests.mjs"
    agents:
      - "deploy=true"
    plugins:
      - seek-oss/aws-sm#v2.3.1:
          region: us-east-2
          env:
            FLY_API_TOKEN: "prod/fly-api-token"
            BUILDKITE_AGENT_TOKEN: "prod/buildkite-agent-token"
            SSH_PRIVATE_RSA_KEY_B64: "prod/buildkite-ssh-private-key"
            TAILSCALE_AUTHKEY: "dev/fly-e2e-test-runner-tailscale-auth-key"
            HASURA_ADMIN_SECRET: "prod/hasura-admin-secret"
            BUILD_USER_ACCESS_KEY_ID:
              secret-id: "prod/build-user"
              json-key: ".access_key_id"
            BUILD_USER_SECRET_ACCESS_KEY:
              secret-id: "prod/build-user"
              json-key: ".secret_access_key"
            BUILDEVENT_APIKEY: honeycomb-api-key
            GITHUB_AUTH_SECRET: "prod/metabase-github-secret"
            BUILDEVENT_APIKEY: honeycomb-api-key
            BUILDEVENT_BUILDKITE_API_TOKEN: buildkite-api-token-honeycomb-build-events
      - replayio/buildevents#adb8a05: ~
      - "ssh://git@github.com/replayio/fly-buildkite-plugin.git#v0.75":
          image: "registry.fly.io/buildkite-backend-e2e-tests:v14"
          organization: "replay"
          cpus: 1
          memory: 2048
          secrets:
            GITHUB_AUTH_SECRET: GITHUB_AUTH_SECRET
            BUILDKITE_AGENT_TOKEN: BUILDKITE_AGENT_TOKEN
            SSH_PRIVATE_RSA_KEY_B64: SSH_PRIVATE_RSA_KEY_B64
            FLY_API_TOKEN: FLY_API_TOKEN
            TAILSCALE_AUTHKEY: TAILSCALE_AUTHKEY
            HASURA_ADMIN_SECRET: HASURA_ADMIN_SECRET
            AWS_SECRET_ACCESS_KEY: BUILD_USER_SECRET_ACCESS_KEY
            AWS_ACCESS_KEY_ID: BUILD_USER_ACCESS_KEY_ID
